name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Install & Cache
        uses: ./.github/actions/setup

  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpx nx format:check
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpx nx affected -t lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpx nx affected -t test

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate NX SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpx nx affected -t build
